export default {
  storyCard: {
    backgroundColor: '#fff',
    width: '24%',
    height: 280,
    textDecoration: 'none',
    borderRadius: 3,
    flex: '0 0 auto',
    margin: '0.5%',
    display: 'flex',
    flexFlow: 'column nowrap',
    padding: 20,
    boxSizing: 'border-box',
    borderTop: '0px solid #ddd',
    borderRight: '1px solid #ddd',
    borderLeft: '1px solid #ddd',
    borderBottom: '2px solid #ddd',
    cursor: 'pointer',
    transition: '100ms ease-out',
    '@media (max-width: 1440px)': {
      width: '32.33%',
    },
    '@media (max-width: 996px)': {
      width: '49%',
    },
    '@media (max-width: 768px)': {
      width: '99%',
      height: 'auto',
    },
    ':hover': {
      boxShadow: '0 4px 14px rgba(0,0,0,0.2)',
      transition: '100ms ease-out',
    },
  },
  activeStoryCard: {
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%,-50%)',
    width: '60vw',
    height: '75vh',
    background: '#fff',
    zIndex: 999999,
    transition: '100ms ease-out',
  },
  labelsWrapper: {
    margin: 'auto -5px 0',
    display: 'flex',
    flexFlow: 'row wrap',
    flex: '0 0 auto',
  },
  labelItem: {
    color: '#aaa',
    fontSize: '0.8em',
    textDecoration: 'underline',
    margin: '0 5px',
    flex: '0 0 auto',
    ':hover': {
      color: '#09a3ed',
    }
  },
  lastUpdated: {
    color: '#ccc',
    fontSize: '0.8em',
    margin: '5px 0',
    fontWeight: 700,
    flex: '0 0 auto',
  },
  storyDetails: {
    listStyle: 'none',
    display: 'flex',
    flex: '0 0 auto',
    flexFlow: 'row wrap',
    justifyContent: 'flex-start',
    margin: '0 0 20px 0',
    padding: 0,
  },
  storyDetail: {
    flex: '0 0 auto',
    color: '#555',
    background: '#eee',
    padding: '3px 6px',
    boxSizing: 'border-box',
    borderRadius: 3,
    fontSize: '0.75em',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: 0,
    margin: 'auto 5px auto 0',
    display: 'flex',
    flexFlow: 'row nowrap',
    justifyContent: 'center',
    alignItems: 'center',
  },
  storyName: {
    fontSize: '1.1em',
    fontWeight: 300,
    color: '#222',
    resize: 'none',
    lineHeight: '1.5',
    borderTop: '0px solid #eee',
    borderLeft: '0px solid #eee',
    borderRight: '0px solid #eee',
    borderBottom: '1px solid #eee',
    height: 140,
    position: 'relative',
    overflowX: 'hidden',
    overflowY: 'hidden',
    marginBottom: 10,
    outline: 'none',
  },
};
