export default {
  base: {
    background: 'rgb(62, 114, 147)',
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
    display: 'flex',
    flexFlow: 'column nowrap',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pp: {
    textTransform: 'uppercase',
    fontWeight: 100,
    margin: '0 auto 10px',
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
  },
  form: {
    display: 'flex',
    flexFlow: 'column nowrap',
    alignItems: 'center',
  },
  input: {
    padding: '10px 15px',
    fontSize: '1.1em',
    textAlign: 'center',
    width: 400,
    maxWidth: '95%',
    boxSizing: 'border-box',
    border: 0,
    outline: 'none',
    borderRadius: 3,
    margin: '10px auto 20px',
  },
  submitBtn: {
    border: 0,
    outline: 'none',
    backgroundColor: '#8bc34a',
    color: '#fff',
    padding: '15px 25px 15px 30px',
    boxSizing: 'border-box',
    borderRadius: 3,
    textTransform: 'uppercase',
    fontSize: '0.9em',
    fontWeight: 700,
    display: 'flex',
    flexFlow: 'row nowrap',
    alignItems: 'center',
    margin: '0 auto 20px',
    cursor: 'pointer',
    transition: '100ms ease-out',
    ':hover': {
      backgroundColor: '#74a639',
      transition: '100ms ease-out',
    }
  },
  copy: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    margin: 'auto',
    color: '#aaa',
    fontWeight: 700,
    fontSize: '0.8em',
    textTransform: 'capitalize',
  }
};
