export default {
  base: {
    background: 'rgb(62, 114, 147)',
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
    display: 'flex',
    flexFlow: 'column nowrap',
    justifyContent: 'center',
    alignItems: 'center',
  },
  form: {
    display: 'flex',
    flexFlow: 'column nowrap',
    alignItems: 'center',
  },
  input: {
    padding: 10,
    fontSize: '1.1em',
    width: 400,
    maxWidth: '95%',
    boxSizing: 'border-box',
    border: 0,
    outline: 'none',
    borderRadius: 3,
    margin: '20px auto',
  },
  submitBtn: {
    border: 0,
    outline: 'none',
    backgroundColor: '#8bc34a',
    color: '#fff',
    padding: '15px 30px',
    boxSizing: 'border-box',
    borderRadius: 3,
    textTransform: 'uppercase',
    fontSize: '0.9em',
    fontWeight: 700,
    margin: '0 auto 20px',
  },
  copy: {
    position: 'absolute',
    bottom: 10,
    left: 'auto',
    right: 'auto',
    margin: 'auto',
    color: '#333',
    fontWeight: 700,
    fontSize: '0.8em',
    textTransform: 'capitalize',
  }
};
