export default {
  bg: {
    backgroundColor: '#333',
    position: 'fixed',
    top: 60,
    right: 0,
    bottom: 0,
    width: '22vw',
    zIndex: 9999,
    paddingTop: 55,
    overflowX: 'hidden',
    overflowY: 'hidden',
    display: 'flex',
    '@media (max-width: 1200px)': {
      width: '28vw',
    },
  },
  title: {
    // backgroundColor: 'rgb(43, 91, 121)',
    backgroundColor: '#333',
    textTransform: 'uppercase',
    color: '#ddd',
    fontSize: '0.85em',
    padding: 20,
    margin: 0,
    width: '22vw',
    boxSizing: 'border-box',
    height: 60,
    display: 'flex',
    alignItems: 'center',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    '@media (max-width: 1200px)': {
      width: '28vw',
    },
  },
  list: {
    listStyle: 'none',
    flex: 1,
    display: 'flex',
    flexFlow: 'column nowrap',
    overflow: 'auto',
    margin: 0,
    padding: '0 0 5px',
    boxSizing: 'border-box',
  },
  listItem: {
    flex: '0 0 auto',
    color: '#666',
    backgroundColor: '#fff',
    borderRadius: 3,
    padding: '10px 35px 10px 10px',
    margin: '3px 10px',
    boxSizing: 'border-box',
    fontSize: '0.85em',
    fontWeight: 700,
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
    height: 60,
    display: 'flex',
    flexFlow: 'column nowrap',
    position: 'relative',
  },
  listItemArrow: {
    position: 'absolute',
    right: 10,
    top: '50%',
    transform: 'translateY(-50%)',
    fontSize: '1.25em',
    color: '#aaa',
  },
  activityTime: {
    padding: 0,
    margin: 'auto 2px',
    boxSizing: 'border-box',
    color: '#ccc',
    fontWeight: 700,
    fontSize: '0.9em',
  },
  activityIcon: {
    margin: '0 0 4px auto',
    fontSize: '1.25em',
    color: '#aaa',
    position: 'relative',
    top: -2
  },
  activityName: {
    padding: 0,
    margin: 'auto 2px',
    boxSizing: 'border-box',
    flex: '0 0 auto',
    '@media (max-width: 1300px)': {
      display: 'none',
    },
  },
  activityInitials: {
    padding: 0,
    margin: 'auto 2px',
    boxSizing: 'border-box',
    display: 'none',
    flex: '0 0 auto',
    '@media (max-width: 1300px)': {
      display: 'block',
    },
  },
  activityHighlight: {
    flex: 1,
    margin: 'auto 2px',
    textOverflow: 'ellipsis',
    overflow: 'hidden',
    whiteSpace: 'nowrap',
  },
  idIcon: {
    backgroundColor: '#eee',
    margin: '0 auto auto 4px',
    padding: '3px 5px',
    boxSizing: 'border-box',
    flex: '0 0 auto',
    fontFamily: 'Source Code pro',
    display: 'flex',
    alignItems: 'center',
    fontSize: '0.9em',
  },
};
