export default {
  base: {
    paddingTop: 60,
    overflow: 'hidden',
    flex: '0 0 auto',
    display: 'flex',
    width: '78vw',
    margin: '0 0 0 auto',
    background: 'transparent',
    '@media (max-width: 1200px)': {
      width: '72vw',
    }
  },
  storiesColumnsWrapper: {
    display: 'flex',
    flex: 1,
    flexFlow: 'row nowrap',
    padding: 0,
    boxSizing: 'border-box',
    overflowX: 'auto',
    overflowY: 'hidden',
    backgroundColor: '#f5f5f5',
  },
  filtersWrapper: {
    position: 'fixed',
    top: 60,
    height: 60,
    width: '78vw',
    right: 0,
    left: '22vw',
    backgroundColor: '#f5f5f5',
    margin: 'auto 0',
    padding: '0 10px',
    boxSizing: 'border-box',
    zIndex: 99,
    display: 'flex',
    flexFlow: 'row nowrap',
    overflowY: 'hidden',
    overflowX: 'auto',
    '@media (max-width: 1200px)': {
      width: '72vw',
    },
  },
  searchInputWrapper: {
    position: 'relative',
    flex: '0 0 auto',
    margin: 'auto 10px auto 0',
  },
  searchInput: {
    backgroundColor: 'rgba(0,0,0,0.1)',
    color: '#000',
    padding: '10px 10px 10px 40px',
    boxSizing: 'border-box',
    borderRadius: 3,
    fontSize: '0.9em',
    border: 0,
    margin: 'auto',
    outline: 'none',
  },
  searchIcon: {
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
    left: 10,
    color: '#000',
  },
  noStories: {
    margin: '40px auto auto',
    textAlign: 'center',
    color: '#aaa',
    fontSize: '1.1em',
  },
  ownerIcon: {
    fontSize: '1.25em',
    margin: 0,
    padding: '5px 0',
    color: '#aaa'
  },
  activeCardBackground: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0,0,0,0.5)',
    zIndex: 99999,
  },
};
